### ISSUE TITLE
Latest version of qi (3.1.1) doesn't install but rather 2.0.1 only works on Python 3.6

### ISSUE THREAD

**Issue by eli-sherling** [aldebaran/libqi-python#19]
The latest version of qi as shown on pypi (3.1.1) did not install on Python 3.11 or 3.10 or 3.9 or 3.8 due to this error.
```
ERROR: Could not find a version that satisfies the requirement qi (from versions: none)
ERROR: No matching distribution found for qi
```
I was forced to install the module in Python 3.6 but it installs version 2.0.1. How can I use the latest version (3.1.1) in Python on Windows?

**Comment by eli-sherling** [comment]
Works as expected in wsl (Python 3.8).

**Comment by nyibbang** [comment]
This is a known issue, our package on PyPi only has wheels for Python 3.5 on Linux. We are working on distributing wheels for more recent versions of Python for future releases of the project. In the meantime, if you require a wheel for a version of Python or an OS that is not available on PyPi, you should be able to build one manually.
