### ISSUE TITLE
Need Help With Instructions

### ISSUE THREAD

**Issue by HarbingerRitual** [aldebaran/libqi-python#21]
Can someone explain to me how to implement these steps?
is it a shell file? I don't get it

![image](https://github.com/aldebaran/libqi-python/assets/24495857/f58f2f47-4299-4329-bbb2-38b730e3beb9)

**Comment by nyibbang** [comment]
Hello @HarbingerRitual.

These are shell commands, yes. They must be executed inside a bash shell, using a terminal.
