### ISSUE TITLE
Inquiry about source code of native API

### ISSUE THREAD

**Issue by PhilipAmadasun** [aldebaran/libqi-python#23]
Might not be the best place to ask this but, I'm part of a research lab using the pepper and we are trying to find the source code of the native APIs (ALAudioPlayer, ALTextToSpeech and so on). Is this source code open source and available anywhere?

**Comment by nyibbang** [comment]
Hello @PhilipAmadasun,

I'm sorry, but the code for these components is proprietary and not open source as far as I know. It's not available at the moment.
