### ISSUE TITLE
ImportError from .qi_python

### ISSUE THREAD

**Issue by matthis-ostfalia** [aldebaran/libqi-python#25]
Hello,

I am using Ubuntu 24 LTS and Python 3.12.3. I have compiled the project myself with conan according to the README (and the workaround with the branch). The target folder is called qi and is in my projects root directory. 

Now, when trying to use the qi Module (i used a simple import qi statement), I get an "ImportError: libboost_filesystem.so.1.83.0: cannot open shared object file: No such file or directory" from the __init__ file on line 11. 

Now this is weird, since a qi_python.so file does exist in the qi folder.

Did I built the project wrong, or maybe imported it wrong? It's my first time using Linux at all, as well as python and Pepper in this "larger" capacity.

**Comment by nyibbang** [comment]
Hello @matthis-ostfalia,

When using Conan, you should have in your `build/generators` folder a `conanrun.sh` script that you can source `source <build-folder>/generators/conanrun.sh`. This script will set the appropriate LD_LIBRARY_PATH so that libraries that reside in the Conan cache are found.

**Comment by matthis-ostfalia** [comment]
Ah, now it works, Thank you a lot!

At first I was confused because I couldn't find the folder you were mentioning. Turns out it was in my .venv folder in a "libqi-python" folder. 

Have a good day!
